### ISSUE TITLE
Logout: Redirects

### ISSUE THREAD

**Issue by maany** [rucio/webui#422] opened 2024-08-01 11:49 UTC
### Description

Currently, when you logout, you just see the output produced by the `/api/auth/logout` endpoint.

<img width="162" alt="image" src="https://github.com/user-attachments/assets/2b16998f-78ec-4335-a794-93a1408bd657">

When a user logs out, the `/api/auth/logout` endpoint or the middleware must 
redirect to the login page

If another identity was present in the session, then the user must be allowed to select it in the login page.
Otherwise, the user can login to a new identity via the normal login workflows

### Rucio WebUI Version

35.0.0

**Comment by MytsV** [comment] 2024-08-08 13:17
Seemed to be a problem with the frontend, fixed it while working on the multiple account header. I will make a pull request shortly

**Comment by MytsV** [comment] 2024-08-15 13:56
> Seemed to be a problem with the frontend, fixed it while working on the multiple account header. I will make a pull request shortly

I recalled the fix for it on the frontend. The old logout button didn't provide the callbackUrl, and the new one uses /dashboard.

Probably the API page should be fixed to perform a redirect even without a callbackUrl

**Comment by MytsV** [comment] 2024-08-15 13:58
I'm not going to commit the fix for the API page because that may not be an intended behavior

**Closed** 2024-08-16 10:06 UTC
Labels: bug
